### ISSUE TITLE
Unused loudness fields are not being written correctly

### ISSUE THREAD

**Issue by david-russo** [MediaArea/BWF_MetaEdit#21]
From *EBU Tech 3285 v2*, page 13:
> "If any of the loudness parameters are not being used then their 16-bit integer values shall be set to 7FFFh, which is a value outside the range of the parameter values."

With BWF MetaEdit 1.3.1, when opening a wave file, setting the BWF version to 2, and saving it, all loudness values are set to `0000h` instead of `7FFFh`, equalling the valid interpreted value of `0.0`, which may not be true for the file.

Besides that, it's a great tool you've got here, thank you for making it available, and maintaining it.

**Comment by JeromeMartinez** [comment]
Oops... Exact, we don't use the right default values.
We'll fix that before releasing a new version.

**Comment by JeromeMartinez** [comment]
[Fixed](https://github.com/MediaArea/BWF_MetaEdit/pull/22).
You can test with [snapshots](https://old.mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/) (versions 20170921+).

**Comment by david-russo** [comment]
Thanks for the quick work, it's passed all my tests.
