### ISSUE TITLE
missing icns in sources

### ISSUE THREAD

**Issue by JeromeMartinez** [MediaArea/BWF_MetaEdit#7]
> macmini:~ jerome$ cd bwfmetaedit/Project/QtCreator/
macmini:QtCreator jerome$ qmake
Info: creating stash file /Users/jerome/bwfmetaedit/Project/QtCreator/.qmake.stash
macmini:QtCreator jerome$ make
make: *** No rule to make target `../../Source/Resource/Image/FADGI/Logo.icns', needed by `BWF MetaEdit.app/Contents/Resources/Logo.icns'.  Stop.

**Comment by g-maxime** [comment]
Fixed by commit 1f6fc2f
